export const Data = [
  {
    name: "181 Hardman Road",
    location: "Mohali",
    area: 200 ,
    price: 5589,
    baths: 2,
    beds: 4,
    type: " House",
    img: "../property1.png",
    id: 1,
  },
  {
    name: "1881 Ajav Road",
    location: "Delhi ",
    area: 200 ,
    price: 7590,
    beds: 2,
    baths: 2,
    type: "Villa ",
    img: "../property2.png",
    id: 2,
  },
  {
    name: "141 Block Road",
    location: "Bombay",
    area: 200 ,
    price: 4599,
    baths: 2,
    beds: 3,
    type: "Bunglow ",
    img: "../property3.png",
    id: 3,
  },
  {
    name: "741 Pin Road",
    location: "Shimla",
    area: 200 ,
    price: 7005,
    baths: 2,
    beds: 1,
    type: "Tree House",
    img: "../property4.png",
    id: 4,
  },

  {
    name: "181 Hardman Road",
    location: "Mohali",
    area: 200,
    price: 3586,
    baths: 2,
    beds: 4,
    type: "House",
    img: "../property1.png",
    id: 5,
  },
  {
    name: "1881 Ajav Road",
    location: "Delhi ",
    area: 200 ,
    price: 7570,
    beds: 3,
    baths: 2,
    type: "Villa ",
    img: "../property2.png",
    id: 6,
  },
  {
    name: "141 Block Road",
    location: "Bombay",
    area: 200 ,
    price: 3599,
    baths: 2,
    beds: 3,
    type: "Bunglow ",
    img: "../property3.png",
    id: 7,
  },
  {
    name: "741 Pin Road",
    location: "Shimla",
    area: 200 ,
    price: 6005,
    baths: 2,
    beds: 7,
    type: "Tree House",
    img: "../property4.png",
    id: 8,
  },
  {
    name: "181 Hardman Road",
    location: "Mohali",
    area: 200 ,
    price: 9889,
    baths: 2,
    beds: 3,
    type: " House",
    img: "../property1.png",
    id: 9,
  },
  {
    name: "1881 Ajav Road",
    location: "Delhi ",
    area: 200 ,
    price: 3580,
    beds: 5,
    baths: 2,
    type: "Villa ",
    img: "../property2.png",
    id: 10,
  },
  {
    name: "141 Block Road",
    location: "Bombay",
    area: 200 ,
    price: 4599,
    baths: 2,
    beds: 3,
    type: "Bunglow ",
    img: "../property3.png",
    id: 11,
  },
  {
    name: "741 Pin Road",
    location: "Shimla",
    area: 200 ,
    price: 7000,
    baths: 2,
    beds: 5,
    type: "Tree House",
    img: "../property4.png",
    id: 12,
  },
  {
    name: "181 Hardman Road",
    location: "Mohali",
    area: 200 ,
    price: 5539,
    baths: 2,
    beds: 4,
    type: " House",
    img: "../property1.png",
    id: 13,
  },
  {
    name: "1881 Ajav Road",
    location: "Delhi ",
    area: 200,
    price: 4560,
    beds: 7,
    baths: 2,
    type: "Villa ",
    img: "../property2.png",
    id: 14,
  },
  {
    name: "141 Block Road",
    location: "Bombay",
    area: 200 ,
    price: 9500,
    baths: 2,
    beds: 5,
    type: "Bunglow ",
    img: "../property3.png",
    id: 15,
  },
  {
    name: "741 Pin Road",
    location: "Shimla",
    area: 200 ,
    price: 7005,
    baths: 2,
    beds: 2,
    type: "Tree House",
    img: "../property4.png",
    id: 16,
  },
];
